const demo = ['localhost','127.0.0.1',''].includes(location.hostname) || location.protocol === 'file:';
const $ = selector => document.querySelector(selector);
const api = '../api/admin';
let catalog, baseline;
const clone = value => JSON.parse(JSON.stringify(value));
const money = value => Number(value).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const safeImage = value => /^assets\/[a-zA-Z0-9._/-]+$/.test(value) || /^https:\/\/[a-zA-Z0-9.-]+(?:\/[a-zA-Z0-9._~:/?#[\]@!$&'()*+,;=%-]*)?$/.test(value);
const imageUrl = value => /^https:\/\//.test(value) ? value : `../${value}`;
async function request(url, options={}) { const response=await fetch(url,{credentials:'same-origin',...options,headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{}),...options.headers}}); const body=await response.json().catch(()=>({})); if(!response.ok) throw Object.assign(new Error(body.erro||'Não foi possível concluir.'),{status:response.status}); return body; }
async function start(){
  if(demo){ $('#demoNotice').hidden=false; const fallback=await fetch('../catalogo-padrao.json').then(r=>r.json()); catalog=JSON.parse(localStorage.getItem('locafort-catalogo-demo')||'null')||fallback; openEditor(); return; }
  try{ catalog=await request(`${api}/catalogo`); openEditor(); }catch(error){ if(error.status===401) $('#login').hidden=false; else { $('#login').hidden=false; $('#loginError').textContent=error.message; } }
}
function openEditor(){ baseline=clone(catalog); $('#login').hidden=true; $('#editor').hidden=false; $('#logout').hidden=demo; fillConditions(); renderProducts(); }
function fillConditions(){const c=catalog.condicoes; $('#weekly').value=c.semanalAPartirDe;$('#deposit').value=c.caucao;$('#initialMonths').value=c.mesesContratoInicial;$('#purchaseWeekly').value=c.intencaoCompraSemanal;$('#purchaseMonths').value=c.intencaoCompraMeses;$('#shortText').value=c.textoCurto||'';}
function readConditions(){return{semanalAPartirDe:+$('#weekly').value,caucao:+$('#deposit').value,mesesContratoInicial:+$('#initialMonths').value,pagamentoSemanalInicio:'a partir da segunda semana',intencaoCompraSemanal:+$('#purchaseWeekly').value,intencaoCompraMeses:+$('#purchaseMonths').value,textoCurto:$('#shortText').value.trim()};}
function newProduct(){return{id:`moto-${Date.now()}`,nome:'Nova moto',categoria:'street',precoTipo:'sob-consulta',precoSemanal:null,imagem:'assets/moto-vermelha.jpeg',texto:'',disponivel:true,ativo:true,ordem:catalog.produtos.length+1};}
function priceText(p){return p.precoTipo==='sob-consulta'?'Valor sob consulta':`A partir de ${money(p.precoSemanal)} por semana`;}
function renderProducts(){const box=$('#products');box.textContent='';catalog.produtos.sort((a,b)=>a.ordem-b.ordem).forEach((product,index)=>{const node=$('#productTemplate').content.firstElementChild.cloneNode(true);node.dataset.id=product.id;node.querySelector('.product-number').textContent=`Moto ${index+1}`;node.querySelectorAll('[data-field]').forEach(input=>{const key=input.dataset.field;input[input.type==='checkbox'?'checked':'value']=product[key]??'';input.addEventListener('input',()=>{product[key]=input.type==='checkbox'?input.checked:key==='precoSemanal'?(input.value===''?null:+input.value):input.value;if(key==='precoTipo'&&input.value==='sob-consulta')product.precoSemanal=null;updatePreview(node,product);});});node.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>action(button.dataset.action,index));updatePreview(node,product);box.append(node);});}
function updatePreview(node,p){const img=node.querySelector('.preview img');img.src=safeImage(p.imagem)?imageUrl(p.imagem):'../assets/frota-locafort.jpeg';node.querySelector('.preview h3').textContent=p.nome||'Nome da moto';node.querySelector('.preview p').textContent=p.texto||'Texto curto da moto';node.querySelector('.preview strong').textContent=p.disponivel?priceText(p):'Indisponível no momento';}
function action(type,index){if(type==='delete'){if(!confirm(`Excluir ${catalog.produtos[index].nome}?`))return;catalog.produtos.splice(index,1);}else{const target=type==='up'?index-1:index+1;if(target<0||target>=catalog.produtos.length)return;[catalog.produtos[index],catalog.produtos[target]]=[catalog.produtos[target],catalog.produtos[index]];}catalog.produtos.forEach((p,i)=>p.ordem=i+1);renderProducts();}
function validate(){catalog.condicoes=readConditions();if(!catalog.produtos.length)throw new Error('Adicione pelo menos uma moto.');if(catalog.produtos.some(p=>!p.nome.trim()||!p.categoria.trim()||!safeImage(p.imagem)||p.precoTipo==='a-partir-de'&&!(p.precoSemanal>=0)))throw new Error('Revise nome, categoria, preço e imagem das motos.');if(Object.values(catalog.condicoes).slice(0,5).some(v=>typeof v==='number'&&(!Number.isFinite(v)||v<0)))throw new Error('Revise os valores gerais.');}
$('#loginForm').onsubmit=async event=>{event.preventDefault();$('#loginError').textContent='';try{await request(`${api}/login`,{method:'POST',body:JSON.stringify({senha:$('#password').value})});catalog=await request(`${api}/catalogo`);openEditor();}catch(error){$('#loginError').textContent=error.message;}};
$('#addProduct').onclick=()=>{catalog.produtos.push(newProduct());renderProducts();document.querySelector('.product:last-child')?.scrollIntoView({behavior:'smooth'});};
$('#discard').onclick=()=>{catalog=clone(baseline);fillConditions();renderProducts();$('#feedback').textContent='Mudanças removidas.';};
$('#save').onclick=async()=>{try{validate();if(demo){localStorage.setItem('locafort-catalogo-demo',JSON.stringify(catalog));baseline=clone(catalog);$('#feedback').textContent='Salvo somente neste navegador (modo demonstração).';}else{const result=await request(`${api}/catalogo`,{method:'POST',body:JSON.stringify(catalog)});catalog=result.catalogo;baseline=clone(catalog);$('#feedback').textContent='Alterações publicadas no catálogo.';}}catch(error){$('#feedback').textContent=error.message;}};
$('#logout').onclick=async()=>{await request(`${api}/logout`,{method:'POST'}).catch(()=>{});location.reload();};start();
