const demo=['localhost','127.0.0.1',''].includes(location.hostname)||location.protocol==='file:',$=s=>document.querySelector(s),api='../api/admin';let catalog,baseline,defaults;
const clone=v=>JSON.parse(JSON.stringify(v)),money=v=>Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0});
const safeMedia=v=>/^assets\/[a-zA-Z0-9._/-]+$/.test(v)||/^\/api\/media\/[a-zA-Z0-9._/-]+$/.test(v)||/^https:\/\/[a-zA-Z0-9.-]+(?:\/[a-zA-Z0-9._~:/?#[\]@!$&'()*+,;=%-]*)?$/.test(v)||(demo&&/^data:(image\/(jpeg|png|webp)|video\/(mp4|webm));base64,/.test(v));
const mediaUrl=v=>/^https:\/\//.test(v)||/^data:/.test(v)?v:`../${v.replace(/^\//,'')}`;
function migrate(saved){const value=saved||{};return{...defaults,...value,versao:2,condicoes:{...defaults.condicoes,...(value.condicoes||{})},site:{...defaults.site,...(value.site||{})},formulario:{...defaults.formulario,...(value.formulario||{})},produtos:(value.produtos||defaults.produtos).map((p,i)=>({cilindrada:'',uso:'',...p,ordem:p.ordem||i+1}))};}
async function request(url,options={}){const headers={Accept:'application/json',...options.headers};if(options.body&&!(options.body instanceof FormData))headers['Content-Type']='application/json';const response=await fetch(url,{credentials:'same-origin',...options,headers});const body=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(body.erro||'Não foi possível concluir.'),{status:response.status});return body;}
async function start(){defaults=await fetch('../catalogo-padrao.json').then(r=>r.json());if(demo){$('#demoNotice').hidden=false;let saved;try{saved=JSON.parse(localStorage.getItem('locafort-catalogo-demo')||'null')}catch{}catalog=migrate(saved);openEditor();return}try{catalog=migrate(await request(`${api}/catalogo`));openEditor()}catch(error){$('#login').hidden=false;$('#loginError').textContent=error.status===401?'':error.message}}
function openEditor(){baseline=clone(catalog);$('#login').hidden=true;$('#editor').hidden=false;$('#logout').hidden=demo;fillAll();}
function tab(name){document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x.dataset.tab===name));document.querySelectorAll('[data-page]').forEach(x=>x.classList.toggle('active',x.dataset.page===name));scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('[data-tab]').forEach(x=>x.onclick=()=>tab(x.dataset.tab));document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>tab(x.dataset.go));
const conditionIds={weekly:'semanalAPartirDe',deposit:'caucao',initialMonths:'mesesContratoInicial',purchaseWeekly:'intencaoCompraSemanal',purchaseMonths:'intencaoCompraMeses',shortText:'textoCurto'};
const siteIds={siteTitle:'tituloPrincipal',siteText:'textoPrincipal',sitePhone:'whatsapp',heroImage:'imagemPrincipal',processImage:'imagemProcesso',finalImage:'imagemFinal',mainVideo:'videoPrincipal'};
const formIds={introTitle:'tituloInicial',introText:'textoInicial',cityTitle:'cidadeTitulo',cityHelp:'cidadeAjuda',ageTitle:'idadeTitulo',ageHelp:'idadeAjuda',cnhTitle:'cnhTitulo',cnhHelp:'cnhAjuda',incomeTitle:'rendaTitulo',incomeHelp:'rendaAjuda',docCnh:'documentoCnh',docAddress:'documentoEndereco',docGov:'documentoGov',approvedTitle:'tituloAprovado',analysisNotice:'avisoAnalise'};
function fillAll(){Object.entries(conditionIds).forEach(([id,key])=>$('#'+id).value=catalog.condicoes[key]??'');Object.entries(siteIds).forEach(([id,key])=>$('#'+id).value=catalog.site[key]??'');Object.entries(formIds).forEach(([id,key])=>$('#'+id).value=catalog.formulario[key]??'');renderProducts();renderMedia();renderOverview()}
function readAll(){Object.entries(conditionIds).forEach(([id,key])=>catalog.condicoes[key]=id==='shortText'?$('#'+id).value.trim():+$('#'+id).value);catalog.condicoes.pagamentoSemanalInicio='a partir da segunda semana';Object.entries(siteIds).forEach(([id,key])=>catalog.site[key]=$('#'+id).value.trim());Object.entries(formIds).forEach(([id,key])=>catalog.formulario[key]=$('#'+id).value.trim());catalog.versao=2}
function renderOverview(){const active=catalog.produtos.filter(p=>p.ativo);$('#activeCount').textContent=active.length;$('#availableCount').textContent=active.filter(p=>p.disponivel).length;$('#weeklySummary').textContent=money(catalog.condicoes.semanalAPartirDe);$('#mediaCount').textContent=Object.values(catalog.site).filter(v=>typeof v==='string'&&safeMedia(v)).length}
function newProduct(){return{id:`moto-${Date.now()}`,nome:'Nova moto',categoria:'street',precoTipo:'sob-consulta',precoSemanal:null,imagem:'assets/moto-vermelha.jpeg',texto:'',cilindrada:'',uso:'',disponivel:true,ativo:true,ordem:catalog.produtos.length+1}}
const price=p=>p.precoTipo==='sob-consulta'?'Valor sob consulta':`A partir de ${money(p.precoSemanal)} por semana`;
function renderProducts(){const box=$('#products');box.textContent='';catalog.produtos.sort((a,b)=>a.ordem-b.ordem).forEach((product,index)=>{const node=$('#productTemplate').content.firstElementChild.cloneNode(true);node.dataset.id=product.id;node.querySelector('.product-number').textContent=`PRODUTO ${index+1}`;node.querySelector('.product-name').textContent=product.nome;node.querySelectorAll('[data-field]').forEach(input=>{const key=input.dataset.field;input[input.type==='checkbox'?'checked':'value']=product[key]??'';input.oninput=()=>{product[key]=input.type==='checkbox'?input.checked:key==='precoSemanal'?(input.value===''?null:+input.value):input.value;if(key==='precoTipo'&&input.value==='sob-consulta')product.precoSemanal=null;node.querySelector('.product-name').textContent=product.nome;updatePreview(node,product)}});node.querySelectorAll('[data-action]').forEach(button=>button.onclick=()=>productAction(button.dataset.action,index));node.querySelector('[data-product-upload]').onchange=e=>uploadFile(e.target.files[0],path=>{product.imagem=path;node.querySelector('[data-field=imagem]').value=path;updatePreview(node,product)},node.querySelector('.preview small'));updatePreview(node,product);box.append(node)})}
function updatePreview(node,p){const img=node.querySelector('.preview img');img.src=safeMedia(p.imagem)?mediaUrl(p.imagem):'../assets/frota-locafort.jpeg';node.querySelector('.preview h3').textContent=p.nome||'Nome da moto';node.querySelector('.preview p').textContent=p.texto||'Descrição curta';node.querySelector('.preview strong').textContent=p.disponivel?price(p):'Indisponível';node.querySelector('.preview small').textContent=[p.cilindrada,p.uso].filter(Boolean).join(' · ')}
function productAction(type,index){if(type==='delete'){if(!confirm(`Excluir ${catalog.produtos[index].nome}?`))return;catalog.produtos.splice(index,1)}else{const target=type==='up'?index-1:index+1;if(target<0||target>=catalog.produtos.length)return;[catalog.produtos[index],catalog.produtos[target]]=[catalog.produtos[target],catalog.produtos[index]]}catalog.produtos.forEach((p,i)=>p.ordem=i+1);renderProducts();renderOverview()}
$('#addProduct').onclick=()=>{catalog.produtos.push(newProduct());renderProducts();renderOverview();requestAnimationFrame(()=>document.querySelector('.product:last-child')?.scrollIntoView({behavior:'smooth',block:'start'}))};
function renderMedia(){document.querySelectorAll('.media-editor').forEach(card=>{const key=card.dataset.media,value=catalog.site[key],media=card.querySelector('img,video');media.src=safeMedia(value)?mediaUrl(value):'';card.querySelector('.media-path').oninput=e=>{catalog.site[key]=e.target.value.trim();renderMedia()};card.querySelector('input[type=file]').onchange=e=>uploadFile(e.target.files[0],path=>{catalog.site[key]=path;card.querySelector('.media-path').value=path;renderMedia()},card.querySelector('small'))})}
async function compressImage(file){if(!file.type.startsWith('image/')||file.size<350000)return file;const bitmap=await createImageBitmap(file),scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d').drawImage(bitmap,0,0,canvas.width,canvas.height);const blob=await new Promise(resolve=>canvas.toBlob(resolve,'image/webp',.82));return new File([blob],file.name.replace(/\.[^.]+$/,'.webp'),{type:'image/webp'})}
const dataUrl=file=>new Promise((resolve,reject)=>{const reader=new FileReader;reader.onload=()=>resolve(reader.result);reader.onerror=reject;reader.readAsDataURL(file)});
async function uploadFile(file,setter,status){if(!file)return;status.textContent='Preparando arquivo…';try{const prepared=await compressImage(file);if(demo){if(prepared.size>1500000)throw new Error('No modo demonstração, use imagem de até 1,5 MB.');setter(await dataUrl(prepared));status.textContent='Prévia salva somente neste navegador.';return}const form=new FormData;form.append('arquivo',prepared);const result=await request(`${api}/media`,{method:'POST',body:form});setter(result.caminho);status.textContent='Upload concluído. Salve as alterações.'}catch(error){status.textContent=error.message.includes('LOCAFORT_MEDIA')?'Upload indisponível: configure o binding LOCAFORT_MEDIA.':error.message}}
function validate(){readAll();if(!catalog.produtos.length)throw new Error('Adicione pelo menos um produto.');if(!/^\d{10,15}$/.test(catalog.site.whatsapp))throw new Error('Confira o WhatsApp com DDI e DDD.');if(Object.values(catalog.site).some(v=>!v||(/[<>]/.test(v))))throw new Error('Revise os textos e mídias do site.');if(['imagemPrincipal','imagemProcesso','imagemFinal','videoPrincipal'].some(k=>!safeMedia(catalog.site[k])))throw new Error('Use caminho assets/, mídia enviada ou URL HTTPS.');if(Object.values(catalog.formulario).some(v=>!v||v.length>160||/[<>]/.test(v)))throw new Error('Preencha todos os textos do formulário.');if(catalog.produtos.some(p=>!p.nome.trim()||!p.categoria.trim()||!safeMedia(p.imagem)||p.precoTipo==='a-partir-de'&&!(p.precoSemanal>=0)))throw new Error('Revise modelo, categoria, preço e imagem dos produtos.');const nums=['semanalAPartirDe','caucao','mesesContratoInicial','intencaoCompraSemanal','intencaoCompraMeses'];if(nums.some(k=>!Number.isFinite(catalog.condicoes[k])||catalog.condicoes[k]<0))throw new Error('Revise os valores das condições.')}
$('#loginForm').onsubmit=async e=>{e.preventDefault();$('#loginError').textContent='';try{await request(`${api}/login`,{method:'POST',body:JSON.stringify({senha:$('#password').value})});catalog=migrate(await request(`${api}/catalogo`));openEditor()}catch(error){$('#loginError').textContent=error.message}};
$('#discard').onclick=()=>{catalog=clone(baseline);fillAll();$('#feedback').textContent='Mudanças removidas.'};$('#save').onclick=async()=>{try{validate();if(demo){localStorage.setItem('locafort-catalogo-demo',JSON.stringify(catalog));baseline=clone(catalog);$('#feedback').textContent='Salvo somente neste navegador.'}else{const result=await request(`${api}/catalogo`,{method:'POST',body:JSON.stringify(catalog)});catalog=migrate(result.catalogo);baseline=clone(catalog);$('#feedback').textContent='Conteúdo atualizado no site.'}renderOverview()}catch(error){$('#feedback').textContent=error.message}};$('#logout').onclick=async()=>{await request(`${api}/logout`,{method:'POST'}).catch(()=>{});location.reload()};start();
